- hosts: staging_mysql

user: ec2-user

sudo: yes

tasks:

- name: Install MySQL

action: yum name=}

with_items:

- MySQL-python

- mysql

- mysql-server

- name: Start the MySQL service

action: service name=mysqld state=started

# 'localhost' must be the last item for idempotency, see

# http://ansible.cc/docs/modules.html#mysql-user

- name: this will update mysql root password for all root accounts

mysql_user: name=root host=} password=} priv=*.*:ALL,GRANT

with_items:

- "}"

- 54.169.67.185

- ::1

- localhost

- name: this will copy .my.cnf file with root password credentials

template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600